version: "3.8"

services:
    database: 
      image: postgres
      container_name: database_ignite
      restart: always
      ports: 
       - 5432:5432
      environment:
       - POSTGRES_USER=docker
       - POSTGRES_PASSWORD=ignite
       - POSTGRES_DB=rentx
      volumes: 
       - pgdata:/data/postgres
        
    app:
     build: .
     container_name: rentx
     ports: 
      - 3333:3333
      - 9229:9229 
     volumes:
      - .:/usr/app
      - /usr/app/node_modules/       
      # https://stackoverflow.com/questions/29181032/add-a-volume-to-docker-but-exclude-a-sub-folder#answer-37898591
      # https://stackoverflow.com/questions/41027833/bcrypt-and-docker-bcrypt-lib-node-invalid-elf-header
      # https://towardsdatascience.com/the-complete-guide-to-docker-volumes-1a06051d2cce
     links:
      - database
     depends_on: 
      - database

volumes:
    pgdata: 
        driver: local   
    
       